### PR TITLE
Fixes condition for Semantic Release 11.

### PR DESCRIPTION
**Pull request by ryasmi**
Hey @bahmutov, thanks for your work here. This plugin doesn't currently support [Semantic-Release 11](https://github.com/semantic-release/semantic-release/releases/tag/v11.0.0). Hopefully this PR goes part or all of the way to fixing that.

### CODE REVIEW

**Comment by bahmutov** [comment]
That's great! But can you update circle.yml as well? Because now we need to run this on Node 8, right?

**Comment by ryasmi** [comment]
Yeah that's right, good spot, I've updated it 👍

**Comment by bahmutov** [comment]
Great, just squashed it and landed it!

**Comment by ryasmi** [comment]
Awesome, thanks @bahmutov 👍

**Pull request merged**
