### PR TITLE
chore(package): relax the sem-rel peer dependency

### LINKED ISSUE #12: Update peer dependency to semantic-release@12

### PR DESCRIPTION
**Pull request by ianwremmel**
Fixes #12

### CODE REVIEW

**Comment by bahmutov** [comment]
thank you @ianwremmel

**Comment by ianwremmel** [comment]
No problem, thanks for merging!

**Comment by Jerska** [comment]
Hey @bahmutov ! Do you believe you could release this change? :)

**Comment by bahmutov** [comment]
published in 2.0.2

**Comment by Jerska** [comment]
Thanks for your reactivity!

**Pull request merged**
