### PR TITLE
Semantic release 11 fixes

### PR DESCRIPTION
**Pull request by pmowrer**
This should hopefully move us past at least the current error.

### CODE REVIEW

**Comment by pmowrer** [comment]
@bahmutov What do you think?

**Comment by bahmutov** [comment]
ok, let's see this in action

**Comment by bahmutov** [comment]
I invited you to be a collaborator on this project - so you are not waiting for me, ok

**Comment by bahmutov** [comment]
Nope, still wrong @pmowrer - do you see the Circle output?

https://circleci.com/gh/bahmutov/condition-circle/28

```
http 200 http://registry.npmjs.org/condition-circle
[Semantic release]: Found version 1.6.0 of package condition-circle with dist-tag latest
[Semantic release]: Retrieving commits since ef4fa7f77d3172e391aaecefa35fb0d4475dc6d7, corresponding to version 1.6.0
[Semantic release]: Found 2 commits since last release
[Semantic release]: Call plugin analyze-commits
found 0 semantic commit(s)
[]
[Semantic release]: An error occurred while running semantic-release: TypeError: cb is not a function
    at analyzeCommits (/home/ubuntu/condition-circle/node_modules/simple-commit-message/src/analyze-commits.js:34:3)
    at simple (eval at <anonymous> (/home/ubuntu/condition-circle/node_modules/simple-commit-message/src/index.js:12:17), <anonymous>:2:25)
    at Object.analyzeCommits (/home/ubuntu/condition-circle/node_modules/semantic-release/lib/plugins/normalize.js:27:26)
    at module.exports (/home/ubuntu/condition-circle/node_modules/semantic-release/index.js:37:30)
```

**Comment by pmowrer** [comment]
Thanks @bahmutov. The error is due to `simple-commit-message` needing to be upgraded to be compatible with `semantic-release` 11.x. It doesn't fit the new plugin format. Filed an issue: https://github.com/bahmutov/simple-commit-message/issues/21

I should be able to work around this meanwhile to get this library back to publishing.

**Pull request merged**
